CREATE TABLE Users (
UserID INT IDENTITY(1,1) PRIMARY KEY,
FirstName NVARCHAR(250) NOT NULL,
LastName NVARCHAR(250) NOT NULL,
UserName NVARCHAR(250) NOT NULL,
Email NVARCHAR(250) NOT NULL,
Password NVARCHAR(250) NOT NULL
);

CREATE TABLE Items (
    ItemID INT IDENTITY(1,1) PRIMARY KEY,
    ItemName NVARCHAR(250) NOT NULL,
    ItemCategory NVARCHAR(250) NOT NULL,
    ItemPrice DECIMAL(18, 2) NOT NULL,
    ItemAvailability NVARCHAR(250) NOT NULL
);
CREATE TABLE Transactions (
    TransactionID INT IDENTITY(1,1) PRIMARY KEY,
    ItemID INT NOT NULL,
    OrderDate DATETIME NOT NULL,
    TotalAmount DECIMAL(18, 2) NOT NULL,
    FOREIGN KEY (ItemID) REFERENCES Items(ItemID)
);
